### ISSUE TITLE
Implementation questions

### ISSUE THREAD

**Issue by nitronoid** [nyotis/SpinXFormGPU#1]
Hi Nik,

I've been digging around this repo for guidance with on my own implementation of the spin-transformation process with CUDA (school project). I was wondering if I could ask you a few questions about solving the two linear systems, currently I use CUSP in a similar way as you, however the performance is very poor in comparison with CHOLMOD. 

This is probably not the place for a discussion that isn't really an issue with this project, but I would appreciate if we could talk via email, you can reach me at this address: jackjdiver@gmail.com

Thanks, 

Jack

**Comment by nyotis** [comment]
Hi Jack,

i would suggest you reach out directly to Keenan Crane who might be able to help, cheers!

Nikos
